USE WiseOwlExercises;
GO

CREATE TABLE dbo.free_sql_exercises
(
    ExerciseID   INT IDENTITY(1,1) PRIMARY KEY,
    Software     NVARCHAR(50)  NOT NULL,
    Topic        NVARCHAR(100) NOT NULL,
    Level        NVARCHAR(50)  NOT NULL,
    Exercise     NVARCHAR(MAX) NOT NULL,
    Number       INT           NOT NULL
);
GO

INSERT INTO dbo.free_sql_exercises (Software, Topic, Level, Exercise, Number)
VALUES
    (N'SQL', N'Using SQL Server', N'Relatively easy', N'Use a script to create the Wise Owl Music database which you can then use to complete a range of other exercises.', 5257),
    (N'SQL', N'Simple Queries', N'Relatively easy', N'Create a query to list out all of the events in the database, with the most recent first.', 4100),
    (N'SQL', N'Simple Queries', N'Relatively easy', N'Create a query using TOP N to show the last 3 categories in a table.', 4101),
    (N'SQL', N'Simple Queries', N'Relatively easy', N'Write a basic SQL Select statement to return an ordered list of musical artists.', 5150),
    (N'SQL', N'Simple Queries', N'Average difficulty', N'Create a query to list the first 5 events in chronological order.', 4102),
    (N'SQL', N'Simple Queries', N'Average difficulty', N'Select and sort a list of albums, showing the top items for different columns.', 5151),
    (N'SQL', N'Simple Queries', N'Harder than average', N'Run two SELECT queries to show the first and last events.', 4103),
    (N'SQL', N'Simple Queries', N'Harder than average', N'Write SQL queries to select and sort a list of venues, showing the top items for different columns.', 5152),
    (N'SQL', N'Setting criteria using WHERE', N'Relatively easy', N'Add criteria to a SQL query to show singles released on different dates.', 5157),
    (N'SQL', N'Setting criteria using WHERE', N'Relatively easy', N'Create a query to list all of the love and relationships events.', 4104),
    (N'SQL', N'Setting criteria using WHERE', N'Relatively easy', N'Use the WHERE clause in a SQL query to return lists of albums filtered by different criteria.', 5153),
    (N'SQL', N'Setting criteria using WHERE', N'Relatively easy', N'Use the WHERE clause in a SQL query to test conditions on text fields for a list of music albums.', 5161),
    (N'SQL', N'Setting criteria using WHERE', N'Average difficulty', N'Use a WHERE clause to show events which contain two given text strings.', 4105),
    (N'SQL', N'Setting criteria using WHERE', N'Average difficulty', N'Use a WHERE clause to show all of the events between two given dates.', 4106),
    (N'SQL', N'Setting criteria using WHERE', N'Average difficulty', N'Use the LIKE operator and wildcard characters in the WHERE clause of a SQL query to return a list of live music venues.', 5163),
    (N'SQL', N'Setting criteria using WHERE', N'Average difficulty', N'Use the WHERE clause in a SQL query to apply criteria to various date fields in a table of live music venues.', 5159),
    (N'SQL', N'Setting criteria using WHERE', N'Average difficulty', N'Use the WHERE clause in SQL queries to combine criteria and filter a list of albums.', 5154),
    (N'SQL', N'Setting criteria using WHERE', N'Average difficulty', N'Write SQL queries using the WHERE clause to test for the existence of NULL in a list of music albums.', 5155),
    (N'SQL', N'Setting criteria using WHERE', N'Harder than average', N'3 challenging queries combining criteria to find possible data anomalies.', 4107),
    (N'SQL', N'Setting criteria using WHERE', N'Harder than average', N'Use wildcards, AND, IN and OR to get a list of events to do with water.', 4108),
    (N'SQL', N'Calculations', N'Relatively easy', N'Add basic expressions to an SQL query to calculate new values from existing columns in a table.', 5170),
    (N'SQL', N'Calculations', N'Relatively easy', N'Create calculated columns in SQL queries which concatenate multiple values to form longer strings.', 5188),
    (N'SQL', N'Calculations', N'Relatively easy', N'List for each event the number of characters in its name.', 4109),
    (N'SQL', N'Calculations', N'Relatively easy', N'Use the CAST and CONVERT functions in SQL queries to control the data types of calculated columns.', 5174),
    (N'SQL', N'Calculations', N'Relatively easy', N'Use the IIF function and CASE expression to create calculated columns in a SQL query based on a list of music albums.', 5178),
    (N'SQL', N'Calculations', N'Relatively easy', N'Use the ISNULL function in SQL queries to convert nulls into meaningful values.', 5183),
    (N'SQL', N'Calculations', N'Average difficulty', N'Add calculated columns to a SQL query to work out the average length of songs in a list of albums.', 5177),
    (N'SQL', N'Calculations', N'Average difficulty', N'Cast numbers as text to allow you to concatenate them together with strings.', 4110),
    (N'SQL', N'Calculations', N'Average difficulty', N'Create calculated columns in SQL Server using the ISNULL function to handle nulls in the data.', 5184),
    (N'SQL', N'Calculations', N'Average difficulty', N'Use CASE expressions in SQL queries to categorise a list of venues based on different criteria.', 5180),
    (N'SQL', N'Calculations', N'Average difficulty', N'Use IsNull, Coalesce and/or CASE WHEN to replace nulls with values.', 4112),
    (N'SQL', N'Calculations', N'Average difficulty', N'Use text functions in SQL queries to clean up messy text data.', 5189),
    (N'SQL', N'Calculations', N'Average difficulty', N'Write a CASE WHEN expression to assign countries to different groups.', 4111),
    (N'SQL', N'Calculations', N'Harder than average', N'Divide events according to whether their first/last letters are the same or vowels.', 4115),
    (N'SQL', N'Calculations', N'Harder than average', N'Use a variety of text functions in SQL queries to manipulate names and addresses of a list of venues.', 5190),
    (N'SQL', N'Calculations', N'Harder than average', N'Use CASE expressions in SQL queries to categorise a list of concerts by ticket sales and cancellations.', 5182),
    (N'SQL', N'Calculations', N'Harder than average', N'Use the % modulus operator and a lot of ingenuity to show how big each country is relative to Wales.', 4114),
    (N'SQL', N'Calculations', N'Harder than average', N'Use the CHARINDEX function multiple times to show the number of characters between two words in a text string.', 4113),
    (N'SQL', N'Calculations using dates', N'Relatively easy', N'Combine the YEAR, CONVERT and FORMAT functions to show events in your year of birth.', 4116),
    (N'SQL', N'Calculations using dates', N'Relatively easy', N'Use SQL date functions to format the release dates of music albums in SQL queries.', 5191),
    (N'SQL', N'Calculations using dates', N'Average difficulty', N'Use date functions in SQL queries to calculate the length of concert tours.', 5192),
    (N'SQL', N'Calculations using dates', N'Average difficulty', N'Use the DATEDIFF and the ABS functions to list the events in order of closeness to when you were born.', 4117),
    (N'SQL', N'Calculations using dates', N'Average difficulty', N'Use the DATENAME and DATEPART functions to show events taking place on Friday 13th of any month/year.', 4118),
    (N'SQL', N'Calculations using dates', N'Harder than average', N'Display full dates, including the correct suffix (1st, 2nd, 3rd, etc).', 4119),
    (N'SQL', N'Calculations using dates', N'Harder than average', N'Use date functions in SQL Server to calculate the lifespan of venues.', 5193),
    (N'SQL', N'Basic joins', N'Relatively easy', N'Create a query containing a join to list out those films whose source is NA.', 4669),
    (N'SQL', N'Basic joins', N'Relatively easy', N'Create a query using the designer, joining 2 tables, then tidy it up and comment its SQL.', 4120),
    (N'SQL', N'Basic joins', N'Relatively easy', N'Use an inner join to link two tables together in a query.', 4031),
    (N'SQL', N'Basic joins', N'Relatively easy', N'Use the Query Designer in SQL Server Management Studio to join multiple tables in a database of music.', 5194),
    (N'SQL', N'Basic joins', N'Average difficulty', N'Create an inner join in a query, then change it to an outer join to show categories having no events.', 4121),
    (N'SQL', N'Basic joins', N'Average difficulty', N'Join two tables together in SQL, using alias table names.', 4032),
    (N'SQL', N'Basic joins', N'Average difficulty', N'Link the continent, country and event tables with inner joins, and then filter by fields from 2 tables.', 4122),
    (N'SQL', N'Basic joins', N'Average difficulty', N'Use basic inner joins to list music albums and their genres before applying filters to the list.', 5195),
    (N'SQL', N'Basic joins', N'Average difficulty', N'Use inner joins to link four tables to show Dr Who enemies by author.', 4033),
    (N'SQL', N'Basic joins', N'Harder than average', N'Add joins to SQL queries to return values from multiple tables in a database of music.', 5196),
    (N'SQL', N'Basic joins', N'Harder than average', N'Use an outer join and criterion to list out the countries which have no corresponding events.', 4123),
    (N'SQL', N'Basic joins', N'Harder than average', N'Use inner joins to link lots of tables together, with a WHERE clause.', 4035),
    (N'SQL', N'More exotic joins', N'Relatively easy', N'Use outer joins in SQL queries to return every row from a table of concert tours.', 5197),
    (N'SQL', N'More exotic joins', N'Average difficulty', N'Use outer joins in SQL queries to return a list of music artists who don''t have any associated concert tours.', 5198),
    (N'SQL', N'More exotic joins', N'Average difficulty', N'Write an SQL outer join to show unmatched records in another table.', 4034),
    (N'SQL', N'More exotic joins', N'Harder than average', N'Create 2 self-joins between a table of families and itself, to show families, their parents and their grandparents.', 4124),
    (N'SQL', N'More exotic joins', N'Harder than average', N'Use inner and outer joins in SQL queries to return lists of albums, artists and concert tours.', 5199),
    (N'SQL', N'Aggregation and grouping', N'Relatively easy', N'Use COUNT, MAX and MIN to show statistics about the rows in the events table.', 4125),
    (N'SQL', N'Aggregation and grouping', N'Relatively easy', N'Use GROUP BY and COUNT to report on the number of events for each category.', 4126),
    (N'SQL', N'Aggregation and grouping', N'Relatively easy', N'Use grouping to show how many episodes each Doctor Who author wrote.', 4036),
    (N'SQL', N'Aggregation and grouping', N'Relatively easy', N'Use SQL queries to group a list of music artists and create statistics related to their albums.', 5201),
    (N'SQL', N'Aggregation and grouping', N'Relatively easy', N'Use the GROUP BY clause in SQL queries to calculate aggregated values for a list of music artists.', 5200),
    (N'SQL', N'Aggregation and grouping', N'Average difficulty', N'Group by 2 fields and use HAVING clause to show popular combinations.', 4037),
    (N'SQL', N'Aggregation and grouping', N'Average difficulty', N'Use SELECT, FROM, WHERE, GROUP BY, HAVING and ORDER BY to list non-European busy countries.', 4127),
    (N'SQL', N'Aggregation and grouping', N'Average difficulty', N'Write SQL queries to group concerts by multiple different geographic columns and create basic aggregations.', 5202),
    (N'SQL', N'Aggregation and grouping', N'Harder than average', N'Combine CAST, AVG, COUNT, LEN, UPPER and LEFT to show the average length of event names by category initial.', 4128),
    (N'SQL', N'Aggregation and grouping', N'Harder than average', N'Use a complex CASE statement to show the number of events for each century, including the CUBE function.', 4129),
    (N'SQL', N'Aggregation and grouping', N'Harder than average', N'Use lots of grouping and criteria to list out year/doctor episode counts.', 4038),
    (N'SQL', N'Aggregation and grouping', N'Harder than average', N'Use SQL queries to group a list of albums by multiple columns and create subtotals for the groups.', 5203),
    (N'SQL', N'Views', N'Relatively easy', N'Use the view designer in SQL Server Management Studio to create a view showing a list of concerts and locations.', 5205),
    (N'SQL', N'Views', N'Relatively easy', N'Use the view designer to create a view, and change it in SQL.', 4039),
    (N'SQL', N'Views', N'Average difficulty', N'Create a view in SQL Server to show a list of number 1 albums and fields from other tables.', 5204),
    (N'SQL', N'Views', N'Average difficulty', N'Create a view in the view designer, tidy up its SQL and use it to select data.', 4130),
    (N'SQL', N'Views', N'Average difficulty', N'Script a view in a query, then use the view designer to edit it.', 4040),
    (N'SQL', N'Views', N'Average difficulty', N'Write a view to combine tables, then use this as a basis for a grouping query.', 4131),
    (N'SQL', N'Views', N'Harder than average', N'Use views based on views to show Doctor Who episodes with only 1 enemy and 1 companion.', 4041),
    (N'SQL', N'Subqueries', N'Relatively easy', N'Use a subquery to show events which happened since the last one for a particular country occurred.', 4132),
    (N'SQL', N'Subqueries', N'Relatively easy', N'Use subqueries in SQL to use aggregate functions as criteria for other queries.', 5206),
    (N'SQL', N'Subqueries', N'Relatively easy', N'Use subqueries to filter with aggregates.', 4227),
    (N'SQL', N'Subqueries', N'Average difficulty', N'Create a correlated subquery to list out all countries having more than 8 events.', 4133),
    (N'SQL', N'Subqueries', N'Average difficulty', N'Use subqueries in SQL to return a list of longer than average music albums.', 5207),
    (N'SQL', N'Subqueries', N'Average difficulty', N'Using sub queries filter the select statement.', 4228),
    (N'SQL', N'Subqueries', N'Harder than average', N'Use nested subqueries in SQL Server to return different sets of results in a database of music.', 5208),
    (N'SQL', N'Subqueries', N'Harder than average', N'Use two subqueries to list all events in neither the last 30 countries or the last 15 categories.', 4134),
    (N'SQL', N'Stored procedures', N'Relatively easy', N'Create a basic SQL stored procedure to return a list of number 1 music albums.', 5214),
    (N'SQL', N'Stored procedures', N'Relatively easy', N'Create a stored procedure to list Dr Who episodes featuring Matt Smith.', 3965),
    (N'SQL', N'Stored procedures', N'Relatively easy', N'Filter the select statement, only show events occuring in August.', 4198),
    (N'SQL', N'Stored procedures', N'Relatively easy', N'Write a basic procedure to list countries in Asia, then make small changes to it.', 4267),
    (N'SQL', N'Stored procedures', N'Average difficulty', N'Create a SQL stored procedure to return a list of rock and roll music albums.', 5215),
    (N'SQL', N'Stored procedures', N'Average difficulty', N'Create a stored procedure to list Dr Who episodes written by Steven Moffat.', 3966),
    (N'SQL', N'Stored procedures', N'Harder than average', N'Create a SQL stored procedure to return a list of concert tours and shows.', 5217),
    (N'SQL', N'Stored procedures', N'Harder than average', N'Create a stored procedure to list Dr Who episodes by frequency in two ways.', 3967),
    (N'SQL', N'Variables', N'Relatively easy', N'Create a simple stored procedure with a single variable to work out your age, and then print it out.', 1772),
    (N'SQL', N'Variables', N'Relatively easy', N'Declare 3 variables to hold different data types.', 4199),
    (N'SQL', N'Variables', N'Relatively easy', N'Use a variable holding a row id to get at the details for a row.', 3968),
    (N'SQL', N'Variables', N'Relatively easy', N'Use variables to store the values used in the WHERE clause of SQL queries.', 5220),
    (N'SQL', N'Variables', N'Relatively easy', N'Using variables create a summary output window of aggregated data.', 4202),
    (N'SQL', N'Variables', N'Average difficulty', N'Filtering a stored procedure using variables.', 4201),
    (N'SQL', N'Variables', N'Average difficulty', N'Read a list of the enemies of Doctor Who into a string variable.', 3969),
    (N'SQL', N'Variables', N'Average difficulty', N'Use variables in SQL to capture the results of aggregation functions in queries of a Music database.', 5222),
    (N'SQL', N'Variables', N'Harder than average', N'Create a list variable to store all the events released in a specified year.', 4203),
    (N'SQL', N'Variables', N'Harder than average', N'Given the name of a Doctor Who, use variables to print details for him.', 3970),
    (N'SQL', N'Variables', N'Harder than average', N'Use variables in SQL to capture statistics about venues in a database of music.', 5225),
    (N'SQL', N'Parameters and return values', N'Relatively easy', N'Add parameters to a SQL stored procedure which returns a list of music albums.', 5226),
    (N'SQL', N'Parameters and return values', N'Relatively easy', N'Get a stored procedure to list the Dr Who episodes for a given enemy.', 3971),
    (N'SQL', N'Parameters and return values', N'Relatively easy', N'Use return values in SQL Server to pass values between stored procedures and return details of music albums.', 5232),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Create a procedure to list out the companions for a given doctor.', 3973),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Create a stored procedure in SQL Server using parameters to filter a list of venues.', 5227),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Create a stored procedure to list Dr Who episodes for a series number, using a default parameter value.', 3972),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Create a stored procedure with NULLs as the default values.', 4213),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Create stored procedures with default values for the parameters.', 4211),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Filter in a stored procedure using a parameter.', 4200),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Use an output parameter to return a list variable of the most eventful continents.', 4224),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Use optional parameters in SQL Server stored procedures to return a list of concerts.', 5229),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Use return values in SQL Server to capture the result of a stored procedure.', 5233),
    (N'SQL', N'Parameters and return values', N'Average difficulty', N'Use return values to bring back an INT return value from a stored procedure.', 4218),
    (N'SQL', N'Parameters and return values', N'Harder than average', N'Count rows and pass the information out of a procedure using output parameters.', 3974),
    (N'SQL', N'Parameters and return values', N'Harder than average', N'Create a SQL stored procedure with multiple optional parameters.', 5231),
    (N'SQL', N'Parameters and return values', N'Harder than average', N'Return a continent name from one procedure, and pass the output value into another.', 4223),
    (N'SQL', N'Parameters and return values', N'Harder than average', N'Return from a stored proecure the name of the country with the most events and how many events there were.', 4220),
    (N'SQL', N'Testing conditions', N'Relatively easy', N'Use IF statements in a SQL stored procedure to return the results of different SELECT statements.', 5234),
    (N'SQL', N'Testing conditions', N'Average difficulty', N'Use IF statements in SQL to validate the values passed in to parameters of a stored procedure.', 5235),
    (N'SQL', N'Testing conditions', N'Average difficulty', N'Use IF to change the SELECT statement that a stored proc runs.', 4204),
    (N'SQL', N'Looping', N'Relatively easy', N'Use a WHILE loop in SQL to create a stored procedure which lists times tables.', 5238),
    (N'SQL', N'Looping', N'Average difficulty', N'Create a loop to perform a count for each year of a given range.', 4205),
    (N'SQL', N'Looping', N'Average difficulty', N'Use a WHILE loop in SQL to count albums reaching different chart positions.', 5239),
    (N'SQL', N'Looping', N'Harder than average', N'Use a loop to show a comma-delimited list of all the films released in each month.', 4206),
    (N'SQL', N'Looping', N'Harder than average', N'Write a nested WHILE loop to find the first N primes.', 1783),
    (N'SQL', N'Scalar functions', N'Relatively easy', N'Count the number of letters for an event using a scalar function.', 4265),
    (N'SQL', N'Scalar functions', N'Relatively easy', N'Create a user-defined function in SQL Server to calculate album sales certifications.', 5241),
    (N'SQL', N'Scalar functions', N'Relatively easy', N'Use a scalar function to include each Dr Who''s incarnation dates in a query.', 3976),
    (N'SQL', N'Scalar functions', N'Average difficulty', N'Create a function to take in any month number and return the month name.', 4207),
    (N'SQL', N'Scalar functions', N'Average difficulty', N'Create a user-defined function in SQL Server to clean up any text passed into it.', 5243),
    (N'SQL', N'Scalar functions', N'Average difficulty', N'Use an SQL function within a query to find out the part number of any Dr Who episode.', 3975),
    (N'SQL', N'Scalar functions', N'Harder than average', N'Create all sorts of scalar functions in SQL to return info about Dr Who episodes from within a query.', 3977),
    (N'SQL', N'Scalar functions', N'Harder than average', N'Create scalar-valued functions in SQL Server to extract information in a list of venues.', 5244),
    (N'SQL', N'Scalar functions', N'Harder than average', N'Use a CASE statement to classify each event according to whether it is the top of its class or not.', 4222),
    (N'SQL', N'Transactions', N'Relatively easy', N'Create a transaction, add Shaun the Sheep as a Doctor Who, then commit or roll this back.', 3978),
    (N'SQL', N'Transactions', N'Relatively easy', N'Use transactions in SQL to control what happens when you modify data in tables.', 5249),
    (N'SQL', N'Transactions', N'Average difficulty', N'Create a transaction to update all countries that aren''t your own, then roll it back.', 4225),
    (N'SQL', N'Transactions', N'Average difficulty', N'Create a transaction which prevents the same event being added multiple times.', 4208),
    (N'SQL', N'Transactions', N'Average difficulty', N'Update the number of Dr Who enemies within a transaction, and commit or roll this back.', 3979),
    (N'SQL', N'Transactions', N'Average difficulty', N'Use the Insert, Update and Delete commands in a single transaction.', 4226),
    (N'SQL', N'Creating tables', N'Relatively easy', N'Use INSERT, UPDATE and DELETE statements in SQL Server to modify data in a table of music artists.', 5246),
    (N'SQL', N'Creating tables', N'Average difficulty', N'Create a table of genres for books using CREATE TABLE, then insert a few rows using INSERT INTO.', 1789),
    (N'SQL', N'Creating tables', N'Average difficulty', N'Store useful information about continents in a new permanent table.', 4229),
    (N'SQL', N'Creating tables', N'Average difficulty', N'Write a SQL query to create a table of companies, and add two rows to it.', 3980),
    (N'SQL', N'Creating tables', N'Average difficulty', N'Write a SQL script to create a table to store movies and use a foreign key to connect it to a table of albums.', 5248),
    (N'SQL', N'Creating tables', N'Harder than average', N'Create a table of genres for books, and create a foreign key constraint linking this to a table of authors.', 1790),
    (N'SQL', N'Temporary tables and table variables', N'Relatively easy', N'Declare a table variable, and copy the Dr Who companions, enemies and doctors into it.', 3982),
    (N'SQL', N'Temporary tables and table variables', N'Relatively easy', N'Try both methods of creating Temporary tables, using INTO and CREATE.', 4232),
    (N'SQL', N'Temporary tables and table variables', N'Relatively easy', N'Use a temporary table in SQL Server to store a list of concerts cancelled due to COVID.', 5250),
    (N'SQL', N'Temporary tables and table variables', N'Relatively easy', N'Write SQL to put Dr Who rows in a temporary table, and add companions and enemies into this.', 3981),
    (N'SQL', N'Temporary tables and table variables', N'Average difficulty', N'Add rows one by one within a loop into a temporary table that you''ve created.', 4231),
    (N'SQL', N'Temporary tables and table variables', N'Average difficulty', N'Use a table variable in SQL Server to store a list of non-charting albums and singles.', 5253),
    (N'SQL', N'Temporary tables and table variables', N'Average difficulty', N'Use a table variable to hold useful information from several sources together.', 4233),
    (N'SQL', N'Temporary tables and table variables', N'Average difficulty', N'Use a table variable to join one set of data to another table.', 4234),
    (N'SQL', N'Temporary tables and table variables', N'Average difficulty', N'Use a temporary table in SQL Server to compile a list of chart-topping albums and singles.', 5251),
    (N'SQL', N'Temporary tables and table variables', N'Average difficulty', N'Use a temporary table or table variable to combine the best Doctor Who episodes into a single table.', 3983),
    (N'SQL', N'Temporary tables and table variables', N'Harder than average', N'Use a table variable or temporary table to build up a list of database problems in a single table.', 3984),
    (N'SQL', N'Temporary tables and table variables', N'Harder than average', N'Use a temporary table or a table variable to collate a set of concert statistics in SQL Server.', 5255),
    (N'SQL', N'Temporary tables and table variables', N'Harder than average', N'Write the names of your stored procedures and functions to a temporary table or table variable.', 3985),
    (N'SQL', N'Table-valued functions', N'Relatively easy', N'Create a table valued function in SQL Server to return statistics about concerts in a given year.', 5256),
    (N'SQL', N'Table-valued functions', N'Relatively easy', N'Create a table-valued function to list events for a given year.', 4263),
    (N'SQL', N'Table-valued functions', N'Relatively easy', N'List episodes made by any given doctor by using a table function in SQL.', 3986),
    (N'SQL', N'Table-valued functions', N'Average difficulty', N'Create a table-valued function in SQL Server to return a list of singles, albums and tours whose names match a search string.', 5258),
    (N'SQL', N'Table-valued functions', N'Average difficulty', N'Create an inline tabled valued function taking two parameters.', 4252),
    (N'SQL', N'Table-valued functions', N'Average difficulty', N'Return a table of episodes for a series number and author, using a table-valued function.', 3987),
    (N'SQL', N'Table-valued functions', N'Harder than average', N'Show episodes, listing companions or enemies according to parameter, using an MSTVF function.', 3988),
    (N'SQL', N'Table-valued functions', N'Harder than average', N'Use a MSTVF to show categories, countries and continents that contain a given vowel.', 4253),
    (N'SQL', N'Derived tables and CTEs', N'Relatively easy', N'Create an expression in a common table expression, and group by this in a query using the CTE.', 4170),
    (N'SQL', N'Derived tables and CTEs', N'Relatively easy', N'Use a Common Table Expression in a SQL query to categorise music albums according to sales certifications.', 5211),
    (N'SQL', N'Derived tables and CTEs', N'Relatively easy', N'Use a Common Table Expression to write a complex query in two distinct parts.', 3989),
    (N'SQL', N'Derived tables and CTEs', N'Relatively easy', N'Use a CTE to group a query by a CASE expression without including it twice.', 4264),
    (N'SQL', N'Derived tables and CTEs', N'Relatively easy', N'Use a derived table subquery in SQL Server to categorise a list of venues by size.', 5260),
    (N'SQL', N'Derived tables and CTEs', N'Average difficulty', N'Create a CTE to show - amazingly easily - events containing the words THIS and THAT, in this order.', 4135),
    (N'SQL', N'Derived tables and CTEs', N'Average difficulty', N'Show enemies appearing in chosen episodes, using a Common Table Expression (CTE).', 3990),
    (N'SQL', N'Derived tables and CTEs', N'Average difficulty', N'Use a basic CTE to hold filtered data before joining onto another table.', 4250),
    (N'SQL', N'Derived tables and CTEs', N'Average difficulty', N'Use a common table expression (CTE) in a SQL query to aggregate information about tracks on albums.', 5212),
    (N'SQL', N'Derived tables and CTEs', N'Average difficulty', N'Use a derived table subquery in SQL Server to display details of venues and statistics for concerts.', 5261),
    (N'SQL', N'Derived tables and CTEs', N'Average difficulty', N'Use a derived table to hold a select statement. Then join another table on.', 4251),
    (N'SQL', N'Derived tables and CTEs', N'Average difficulty', N'Use linked CTEs to show continents having many countries but few events.', 4266),
    (N'SQL', N'Derived tables and CTEs', N'Harder than average', N'Create a CTE - common table expression - to display breadcrumbs using recursion.', 1879),
    (N'SQL', N'Derived tables and CTEs', N'Harder than average', N'Create two CTEs to hold data before joining them together.', 4249),
    (N'SQL', N'Derived tables and CTEs', N'Harder than average', N'For each combination of the top 3 categories and top 3 countries, count the number of events using CTEs.', 4136),
    (N'SQL', N'Derived tables and CTEs', N'Harder than average', N'Use a series of CTEs to show categories for countries for events not containing the letters OWL.', 4137),
    (N'SQL', N'Derived tables and CTEs', N'Harder than average', N'Use common table expressions, subqueries or any other technique to solve a complex query.', 3991),
    (N'SQL', N'Derived tables and CTEs', N'Harder than average', N'Use CTEs in a SQL query to return details of venues and statistics of shows held at them.', 5213),
    (N'SQL', N'Derived tables and CTEs', N'Harder than average', N'Use derived table subqueries in SQL Server to merge the results of different grouping queries into a single result set.', 5262),
    (N'SQL', N'Dynamic SQL', N'Relatively easy', N'Create a stored procedure which can change the name of the table in the FROM clause.', 4219),
    (N'SQL', N'Dynamic SQL', N'Average difficulty', N'Create a query which selects whatever columns, sort order and table you pass in as parameters, using dynamic SQL.', 1804),
    (N'SQL', N'Dynamic SQL', N'Average difficulty', N'Write a procedure using EXEC which varies the sort column according to the parameter value passed.', 3992),
    (N'SQL', N'Dynamic SQL', N'Harder than average', N'Using a comma-delimited list variable filter another select statement using dynamic SQL.', 4221),
    (N'SQL', N'Pivots', N'Average difficulty', N'Show the number of episodes by year and series number as pivoted data.', 4168),
    (N'SQL', N'Pivots', N'Harder than average', N'Show complete list of column headers using dynamic SQL and the PIVOT command.', 4169),
    (N'SQL', N'Triggers', N'Average difficulty', N'Use a trigger to log when anyone adds, deletes or renames a country.', 4275),
    (N'SQL', N'Triggers', N'Harder than average', N'Prevent anyone deleting events in the UK with an INSTEAD OF DELETE trigger.', 4274);
GO